version: '3.9'
name: myproject
services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  my_project:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: django
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    environment:
      WAIT_HOSTS: postgres:5432
