# Generated by Django 5.0.1 on 2024-02-06 13:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="bid",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
