# Generated by Django 5.0.1 on 2024-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='default/no_image.jpg', upload_to='user_images/'),
        ),
    ]
